Stock.create!([
  {name: "1-800 FLOWERS.COM, Inc.", index: "Nasdaq", symbol: "FLWS", currentEPS: "0.43", dividends_per_share: "N/A", day_high_price: "7.88", day_low_price: "7.54", book_value: "3.99", price_to_book_ratio: "1.89"},
  {name: "Activision Blizzard, Inc", index: "Nasdaq", symbol: "ATVI", currentEPS: "1.80", dividends_per_share: "0.26", day_high_price: "29.65", day_low_price: "28.55", book_value: "11.01", price_to_book_ratio: "2.55"},
  {name: "BioLife Solutions, Inc.", index: "Nasdaq", symbol: "BLFS", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "California First National Bancorp", index: "Nasdaq", symbol: "CFNB", currentEPS: "0.62", dividends_per_share: "0.44", day_high_price: "13.60", day_low_price: "13.35", book_value: "17.84", price_to_book_ratio: "0.78"},
  {name: "Electronic Arts Inc.", index: "Nasdaq", symbol: "EA", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Facebook, Inc.", index: "Nasdaq", symbol: "FB", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Garmin Ltd.", index: "Nasdaq", symbol: "GRMN", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Hasbro, Inc.", index: "Nasdaq", symbol: "HAS", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Iridium Communications Inc", index: "Nasdaq", symbol: "IRDM", currentEPS: "0.79", dividends_per_share: "N/A", day_high_price: "7.28", day_low_price: "6.94", book_value: "13.70", price_to_book_ratio: "0.51"},
  {name: "JetBlue Airways Corporation", index: "Nasdaq", symbol: "JBLU", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Kona Grill, Inc.", index: "Nasdaq", symbol: "KONA", currentEPS: "-0.39", dividends_per_share: "N/A", day_high_price: "13.56", day_low_price: "13.02", book_value: "5.72", price_to_book_ratio: "2.26"},
  {name: "LendingTree, Inc.", index: "Nasdaq", symbol: "TREE", currentEPS: "2.78", dividends_per_share: "0.00", day_high_price: "65.13", day_low_price: "59.82", book_value: "9.77", price_to_book_ratio: "6.12"},
  {name: "Morningstar, Inc.", index: "Nasdaq", symbol: "MORN", currentEPS: "2.95", dividends_per_share: "0.88", day_high_price: "79.27", day_low_price: "76.14", book_value: "15.37", price_to_book_ratio: "4.93"},
  {name: "Navient Corporation", index: "Nasdaq", symbol: "NAVI", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Overstock.com, Inc.", index: "Nasdaq", symbol: "OSTK", currentEPS: "0.61", dividends_per_share: "N/A", day_high_price: "14.24", day_low_price: "13.32", book_value: "5.96", price_to_book_ratio: "2.27"},
  {name: "Panera Bread Company", index: "Nasdaq", symbol: "PNRA", currentEPS: "6.54", dividends_per_share: "N/A", day_high_price: "204.45", day_low_price: "200.20", book_value: "22.57", price_to_book_ratio: "8.83"},
  {name: "QUALCOMM Incorporated", index: "Nasdaq", symbol: "QCOM", currentEPS: "4.10", dividends_per_share: "1.92", day_high_price: "46.83", day_low_price: "45.40", book_value: "20.23", price_to_book_ratio: "2.20"},
  {name: "Rent-A-Center Inc.", index: "Nasdaq", symbol: "RCII", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Ryanair Holdings plc", index: "Nasdaq", symbol: "RYAAY", currentEPS: "5.25", dividends_per_share: "3.32", day_high_price: "79.26", day_low_price: "77.58", book_value: "17.34", price_to_book_ratio: "4.52"},
  {name: "Seagate Technology PLC", index: "Nasdaq", symbol: "STX", currentEPS: "2.76", dividends_per_share: "2.52", day_high_price: "31.53", day_low_price: "29.85", book_value: "6.15", price_to_book_ratio: "4.86"},
  {name: "Starbucks Corporation", index: "Nasdaq", symbol: "SBUX", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "TrueCar, Inc.", index: "Nasdaq", symbol: "TRUE", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Urban Outfitters, Inc.", index: "Nasdaq", symbol: "URBN", currentEPS: "1.74", dividends_per_share: "N/A", day_high_price: "26.13", day_low_price: "24.90", book_value: "9.64", price_to_book_ratio: "2.57"},
  {name: "Viacom Inc.", index: "Nasdaq", symbol: "VIA", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Wingstop Inc.", index: "Nasdaq", symbol: "WING", currentEPS: "0.45", dividends_per_share: "N/A", day_high_price: "22.89", day_low_price: "22.00", book_value: "-0.50", price_to_book_ratio: "N/A"},
  {name: "Xencor, Inc.", index: "Nasdaq", symbol: "XNCR", currentEPS: "-0.97", dividends_per_share: "N/A", day_high_price: "11.67", day_low_price: "10.87", book_value: "3.79", price_to_book_ratio: "2.98"},
  {name: "Yahoo! Inc.", index: "Nasdaq", symbol: "YHOO", currentEPS: "0.52", dividends_per_share: "N/A", day_high_price: "29.44", day_low_price: "27.94", book_value: "30.78", price_to_book_ratio: "0.88"},
  {name: "Zynga Inc.", index: "Nasdaq", symbol: "ZNGA", currentEPS: "0.02", dividends_per_share: "N/A", day_high_price: "1.96", day_low_price: "1.82", book_value: "1.94", price_to_book_ratio: "0.94"},
  {name: "3M Company", index: "NYSE", symbol: "MMM", currentEPS: "8.23", dividends_per_share: "4.44", day_high_price: "155.90", day_low_price: "154.26", book_value: "19.22", price_to_book_ratio: "8.01"},
  {name: "Abercrombie & Fitch Company", index: "NYSE", symbol: "ANF", currentEPS: "1.04", dividends_per_share: "0.80", day_high_price: "25.54", day_low_price: "24.53", book_value: "18.84", price_to_book_ratio: "1.31"},
  {name: "Bank of America Corporation", index: "NYSE", symbol: "BAC", currentEPS: "1.50", dividends_per_share: "0.20", day_high_price: "12.39", day_low_price: "12.11", book_value: "22.54", price_to_book_ratio: "0.53"},
  {name: "CarMax Inc", index: "NYSE", symbol: "KMX", currentEPS: "3.05", dividends_per_share: "N/A", day_high_price: "46.19", day_low_price: "44.13", book_value: "14.74", price_to_book_ratio: "2.96"},
  {name: "Deere & Company", index: "NYSE", symbol: "DE", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Exxon Mobil Corporation", index: "NYSE", symbol: "XOM", currentEPS: "2.48", dividends_per_share: "2.92", day_high_price: "81.85", day_low_price: "80.28", book_value: "41.01", price_to_book_ratio: "1.98"},
  {name: "FedEx Corporation", index: "NYSE", symbol: "FDX", currentEPS: "10.57", dividends_per_share: "1.00", day_high_price: "132.74", day_low_price: "129.12", book_value: "54.39", price_to_book_ratio: "2.36"},
  {name: "General Electric Company", index: "NYSE", symbol: "GE", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Honda Motor Company, Ltd.", index: "NYSE", symbol: "HMC", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "ITT Corporation", index: "NYSE", symbol: "ITT", currentEPS: "2.62", dividends_per_share: "0.50", day_high_price: "32.50", day_low_price: "31.65", book_value: "15.22", price_to_book_ratio: "2.12"},
  {name: "J P Morgan Chase & Co", index: "NYSE", symbol: "JPM", currentEPS: "6.07", dividends_per_share: "1.76", day_high_price: "58.60", day_low_price: "57.64", book_value: "60.29", price_to_book_ratio: "0.95"},
  {name: "Kellogg Company", index: "NYSE", symbol: "K", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Lockheed Martin Corporation", index: "NYSE", symbol: "LMT", currentEPS: "11.80", dividends_per_share: "6.60", day_high_price: "209.49", day_low_price: "206.85", book_value: "10.22", price_to_book_ratio: "20.16"},
  {name: "Morgan Stanley", index: "NYSE", symbol: "MS", currentEPS: "2.88", dividends_per_share: "0.60", day_high_price: "24.14", day_low_price: "23.21", book_value: "34.97", price_to_book_ratio: "0.66"},
  {name: "Northrop Grumman Corporation", index: "NYSE", symbol: "NOC", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Oshkosh Corporation", index: "NYSE", symbol: "OSK", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Pandora Media, Inc.", index: "NYSE", symbol: "P", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Quaker Chemical Corporation", index: "NYSE", symbol: "KWR", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Ralph Lauren Corporation", index: "NYSE", symbol: "RL", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Sonoco Products Company", index: "NYSE", symbol: "SON", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Time Warner Cable Inc", index: "NYSE", symbol: "TWC", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "United Parcel Service, Inc.", index: "NYSE", symbol: "UPS", currentEPS: "5.77", dividends_per_share: "3.12", day_high_price: "99.02", day_low_price: "97.51", book_value: "2.16", price_to_book_ratio: "44.96"},
  {name: "Valero Energy Corporation", index: "NYSE", symbol: "VLO", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Wells Fargo & Company", index: "NYSE", symbol: "WFC", currentEPS: "4.28", dividends_per_share: "1.50", day_high_price: "48.41", day_low_price: "47.57", book_value: "33.83", price_to_book_ratio: "1.40"},
  {name: "Xerox Corporation", index: "NYSE", symbol: "XRX", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Yelp Inc.", index: "NYSE", symbol: "YELP", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Zendesk, Inc.", index: "NYSE", symbol: "ZEN", currentEPS: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
])
