Stock.create!([
  {name: "1-800 FLOWERS.COM, Inc.", exchange: "Nasdaq", symbol: "FLWS", current_eps: "0.43", dividends_per_share: "N/A", day_high_price: "7.88", day_low_price: "7.54", book_value: "3.99", price_to_book_ratio: "1.89"},
  {name: "Activision Blizzard, Inc", exchange: "Nasdaq", symbol: "ATVI", current_eps: "1.80", dividends_per_share: "0.26", day_high_price: "29.65", day_low_price: "28.55", book_value: "11.01", price_to_book_ratio: "2.55"},
  {name: "BioLife Solutions, Inc.", exchange: "Nasdaq", symbol: "BLFS", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "California First National Bancorp", exchange: "Nasdaq", symbol: "CFNB", current_eps: "0.62", dividends_per_share: "0.44", day_high_price: "13.60", day_low_price: "13.35", book_value: "17.84", price_to_book_ratio: "0.78"},
  {name: "Electronic Arts Inc.", exchange: "Nasdaq", symbol: "EA", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Facebook, Inc.", exchange: "Nasdaq", symbol: "FB", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Garmin Ltd.", exchange: "Nasdaq", symbol: "GRMN", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Hasbro, Inc.", exchange: "Nasdaq", symbol: "HAS", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Iridium Communications Inc", exchange: "Nasdaq", symbol: "IRDM", current_eps: "0.79", dividends_per_share: "N/A", day_high_price: "7.28", day_low_price: "6.94", book_value: "13.70", price_to_book_ratio: "0.51"},
  {name: "JetBlue Airways Corporation", exchange: "Nasdaq", symbol: "JBLU", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Kona Grill, Inc.", exchange: "Nasdaq", symbol: "KONA", current_eps: "-0.39", dividends_per_share: "N/A", day_high_price: "13.56", day_low_price: "13.02", book_value: "5.72", price_to_book_ratio: "2.26"},
  {name: "LendingTree, Inc.", exchange: "Nasdaq", symbol: "TREE", current_eps: "2.78", dividends_per_share: "0.00", day_high_price: "65.13", day_low_price: "59.82", book_value: "9.77", price_to_book_ratio: "6.12"},
  {name: "Morningstar, Inc.", exchange: "Nasdaq", symbol: "MORN", current_eps: "2.95", dividends_per_share: "0.88", day_high_price: "79.27", day_low_price: "76.14", book_value: "15.37", price_to_book_ratio: "4.93"},
  {name: "Navient Corporation", exchange: "Nasdaq", symbol: "NAVI", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Overstock.com, Inc.", exchange: "Nasdaq", symbol: "OSTK", current_eps: "0.61", dividends_per_share: "N/A", day_high_price: "14.24", day_low_price: "13.32", book_value: "5.96", price_to_book_ratio: "2.27"},
  {name: "Panera Bread Company", exchange: "Nasdaq", symbol: "PNRA", current_eps: "6.54", dividends_per_share: "N/A", day_high_price: "204.45", day_low_price: "200.20", book_value: "22.57", price_to_book_ratio: "8.83"},
  {name: "QUALCOMM Incorporated", exchange: "Nasdaq", symbol: "QCOM", current_eps: "4.10", dividends_per_share: "1.92", day_high_price: "46.83", day_low_price: "45.40", book_value: "20.23", price_to_book_ratio: "2.20"},
  {name: "Rent-A-Center Inc.", exchange: "Nasdaq", symbol: "RCII", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Ryanair Holdings plc", exchange: "Nasdaq", symbol: "RYAAY", current_eps: "5.25", dividends_per_share: "3.32", day_high_price: "79.26", day_low_price: "77.58", book_value: "17.34", price_to_book_ratio: "4.52"},
  {name: "Seagate Technology PLC", exchange: "Nasdaq", symbol: "STX", current_eps: "2.76", dividends_per_share: "2.52", day_high_price: "31.53", day_low_price: "29.85", book_value: "6.15", price_to_book_ratio: "4.86"},
  {name: "Starbucks Corporation", exchange: "Nasdaq", symbol: "SBUX", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "TrueCar, Inc.", exchange: "Nasdaq", symbol: "TRUE", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Urban Outfitters, Inc.", exchange: "Nasdaq", symbol: "URBN", current_eps: "1.74", dividends_per_share: "N/A", day_high_price: "26.13", day_low_price: "24.90", book_value: "9.64", price_to_book_ratio: "2.57"},
  {name: "Viacom Inc.", exchange: "Nasdaq", symbol: "VIA", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Wingstop Inc.", exchange: "Nasdaq", symbol: "WING", current_eps: "0.45", dividends_per_share: "N/A", day_high_price: "22.89", day_low_price: "22.00", book_value: "-0.50", price_to_book_ratio: "N/A"},
  {name: "Xencor, Inc.", exchange: "Nasdaq", symbol: "XNCR", current_eps: "-0.97", dividends_per_share: "N/A", day_high_price: "11.67", day_low_price: "10.87", book_value: "3.79", price_to_book_ratio: "2.98"},
  {name: "Yahoo! Inc.", exchange: "Nasdaq", symbol: "YHOO", current_eps: "0.52", dividends_per_share: "N/A", day_high_price: "29.44", day_low_price: "27.94", book_value: "30.78", price_to_book_ratio: "0.88"},
  {name: "Zynga Inc.", exchange: "Nasdaq", symbol: "ZNGA", current_eps: "0.02", dividends_per_share: "N/A", day_high_price: "1.96", day_low_price: "1.82", book_value: "1.94", price_to_book_ratio: "0.94"},
  {name: "3M Company", exchange: "NYSE", symbol: "MMM", current_eps: "8.23", dividends_per_share: "4.44", day_high_price: "155.90", day_low_price: "154.26", book_value: "19.22", price_to_book_ratio: "8.01"},
  {name: "Abercrombie & Fitch Company", exchange: "NYSE", symbol: "ANF", current_eps: "1.04", dividends_per_share: "0.80", day_high_price: "25.54", day_low_price: "24.53", book_value: "18.84", price_to_book_ratio: "1.31"},
  {name: "Bank of America Corporation", exchange: "NYSE", symbol: "BAC", current_eps: "1.50", dividends_per_share: "0.20", day_high_price: "12.39", day_low_price: "12.11", book_value: "22.54", price_to_book_ratio: "0.53"},
  {name: "CarMax Inc", exchange: "NYSE", symbol: "KMX", current_eps: "3.05", dividends_per_share: "N/A", day_high_price: "46.19", day_low_price: "44.13", book_value: "14.74", price_to_book_ratio: "2.96"},
  {name: "Deere & Company", exchange: "NYSE", symbol: "DE", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Exxon Mobil Corporation", exchange: "NYSE", symbol: "XOM", current_eps: "2.48", dividends_per_share: "2.92", day_high_price: "81.85", day_low_price: "80.28", book_value: "41.01", price_to_book_ratio: "1.98"},
  {name: "FedEx Corporation", exchange: "NYSE", symbol: "FDX", current_eps: "10.57", dividends_per_share: "1.00", day_high_price: "132.74", day_low_price: "129.12", book_value: "54.39", price_to_book_ratio: "2.36"},
  {name: "General Electric Company", exchange: "NYSE", symbol: "GE", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Honda Motor Company, Ltd.", exchange: "NYSE", symbol: "HMC", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "ITT Corporation", exchange: "NYSE", symbol: "ITT", current_eps: "2.62", dividends_per_share: "0.50", day_high_price: "32.50", day_low_price: "31.65", book_value: "15.22", price_to_book_ratio: "2.12"},
  {name: "J P Morgan Chase & Co", exchange: "NYSE", symbol: "JPM", current_eps: "6.07", dividends_per_share: "1.76", day_high_price: "58.60", day_low_price: "57.64", book_value: "60.29", price_to_book_ratio: "0.95"},
  {name: "Kellogg Company", exchange: "NYSE", symbol: "K", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Lockheed Martin Corporation", exchange: "NYSE", symbol: "LMT", current_eps: "11.80", dividends_per_share: "6.60", day_high_price: "209.49", day_low_price: "206.85", book_value: "10.22", price_to_book_ratio: "20.16"},
  {name: "Morgan Stanley", exchange: "NYSE", symbol: "MS", current_eps: "2.88", dividends_per_share: "0.60", day_high_price: "24.14", day_low_price: "23.21", book_value: "34.97", price_to_book_ratio: "0.66"},
  {name: "Northrop Grumman Corporation", exchange: "NYSE", symbol: "NOC", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Oshkosh Corporation", exchange: "NYSE", symbol: "OSK", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Pandora Media, Inc.", exchange: "NYSE", symbol: "P", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Quaker Chemical Corporation", exchange: "NYSE", symbol: "KWR", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Ralph Lauren Corporation", exchange: "NYSE", symbol: "RL", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Sonoco Products Company", exchange: "NYSE", symbol: "SON", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Time Warner Cable Inc", exchange: "NYSE", symbol: "TWC", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "United Parcel Service, Inc.", exchange: "NYSE", symbol: "UPS", current_eps: "5.77", dividends_per_share: "3.12", day_high_price: "99.02", day_low_price: "97.51", book_value: "2.16", price_to_book_ratio: "44.96"},
  {name: "Valero Energy Corporation", exchange: "NYSE", symbol: "VLO", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Wells Fargo & Company", exchange: "NYSE", symbol: "WFC", current_eps: "4.28", dividends_per_share: "1.50", day_high_price: "48.41", day_low_price: "47.57", book_value: "33.83", price_to_book_ratio: "1.40"},
  {name: "Xerox Corporation", exchange: "NYSE", symbol: "XRX", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Yelp Inc.", exchange: "NYSE", symbol: "YELP", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
  {name: "Zendesk, Inc.", exchange: "NYSE", symbol: "ZEN", current_eps: nil, dividends_per_share: nil, day_high_price: nil, day_low_price: nil, book_value: nil, price_to_book_ratio: nil},
])
